config/routes.rb
Rails.application.routes.draw do
  # Root route
  authenticated :user do
    root to: 'meetings#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'pages#index'
  end

  # Authentication
  devise_for :users, skip: [:registrations, :passwords, :confirmations],  controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  as :user do
    # Omniauth
    match 'auth/:provider/callback', to: 'users/sessions#create', via: [:get, :post]
    match 'auth/failure', to: redirect('/'), via: [:get, :post]
  end

  get '/connect_slack', to: 'pages#connect_slack'
  
  resources :users, only: [:update, :edit]

  # Meetings resource
  resources :meetings, only: :index
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :events
  has_many :users, through: :events
  default_scope { where("starts_at >= ?", Time.now.utc).order(starts_at: :desc) }

  def self.meeting_attrs(event, user_id)
    {
      meeting_id: event.id,
      user_id: user_id,
      starts_at: event.start.date_time,
      ends_at: event.end.date_time,
      info: event.to_json
    }
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  def index
    @grouped_meetings = current_user.meetings.where("starts_at <= ?", current_user.from_time).to_a.group_by_day(&:starts_at)
  end

  def show
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
  def random_color
    colors = ['green', 'red', 'pink', 'yellow', 'dark-green', 'orange', 'blue']
    colors.sample
  end
end

app/views/meetings/_meeting.html.erb
<div class="meetings-block" id="meeting-<%= meeting.id %>">
  <div class="meetings-content">
    <div class="card full-width">
      <div class="colored-counter">
        <span class="circle <%= random_color %>"></span>
      </div>
      <div class="card-description">
        <div class="card-header">
          <h5>
            <%= link_to(meeting.info["hangout_link"], target: '_blank') do %>
              <%= meeting.info["summary"] %>
            <% end %>
          </h5>
        </div>
        <div class="info">
          <% if meeting.info["location"] %>
            <address class="address">
              <i class="icon-location"></i>
              <%= meeting.info["location"] %>
            </address>
          <% end %>
        </div>
        <div class="attendees">
          <div class="attendee">
            <small>
              <p><%= meeting.info["attendees"].map{|a| a["display_name"]}.to_sentence %></p>
            </small>
          </div>
        </div>
      </div>
      <div class="via">
        <i class="icon-clock"></i>
        <%= local_time(meeting.starts_at, format: '%l:%M%P', class: 'start-time') %> -
        <%= local_time(meeting.ends_at, format: '%l:%M%P', class: 'end-time') %>
      </div>
    </div>
  </div>
</div>

app/views/meetings/_meetings.html.erb
<% grouped_meetings.each do |date, meetings| %>
  <% if meetings.length > 0 %>
    <div class="separator">
      <h3>
        <div class="count pull-left">
          <%= pluralize(meetings.length, 'meeting') %>
        </div>
        <div class="date pull-right">
          <%= local_date(date, '%e %b') %>
        </div>
      </h3>
    </div>
    <section class="meetings">
      <%= render partial: 'meetings/meeting', collection: meetings %>
    </section>
  <% end %>
<% end %>

app/views/meetings/index.html.erb
<div class="meetings-container center">
  <% if user_signed_in? %>
    <div class="weekspan">
      <div class="date">
        <h1>
          <%= local_date(Time.now, '%e') %>
          <span class="month">
            <%= local_date(Time.now, '%b') %> /
            <%= local_date(Time.now, '%A') %>
          </span>
        </h1>
      </div>
      <div class="owner">
        <%= image_tag(current_user.avatar.url(:mini)) %>
        <span class="name">
          <%= 'ohai, ' + current_user.first_name %>
        </span>
        <%= link_to(edit_user_path(current_user), class: 'preference') do %>
          <i class="icon-cog"></i>
        <% end %>
      </div>
    </div>
    <%= render partial: 'meetings/meetings', locals: { grouped_meetings: @grouped_meetings } %>
    <% else %>
      <%= link_to "Sign in with Google", user_omniauth_authorize_path(:google) %>
      <%= link_to "Sign in with Slack", user_omniauth_authorize_path(:slack) %>
    <% end %>
</div>